"""Automatic adapter generator: AutoGen team → TraceCore agent.

Given an AutoGen team definition (model, agents, system messages) and a
TraceCore task reference, generates a complete TraceCore-compatible agent
file that implements ``reset/observe/act``.

Usage::

    from agent_bench.integrations.autogen_adapter import generate_agent

    generate_agent(
        task_ref="rate_limited_api@1",
        model="gpt-4o",
        agents=[
            {"name": "Worker", "system_message": "Execute tools precisely."},
            {"name": "Supervisor", "system_message": "Review actions. Correct mistakes."},
        ],
        output_path="agents/my_autogen_agent.py",
    )

The generated agent:
- Implements ``reset``, ``observe``, ``act``
- Builds a step prompt from the observation with the task's action schema
- Runs a short AutoGen RoundRobinGroupChat conversation to decide the next action
- Extracts valid action JSON from the team's output
- Falls back to ``wait`` if extraction fails
"""

from __future__ import annotations

import inspect
import textwrap
from pathlib import Path

from agent_bench.runner.runner import _action_schema, _parse_task_ref
from agent_bench.tasks.loader import load_task


def _get_action_schema_for_task(task_ref: str) -> dict[str, list[str]]:
    """Load a task and return its action schema (action_name -> [param_names])."""
    task_id, version = _parse_task_ref(task_ref)
    task = load_task(task_id, version)
    actions_mod = task["actions"]
    return _action_schema(actions_mod)


def _build_agent_source(
    *,
    class_name: str,
    model: str,
    agents: list[dict],
    action_schema: dict[str, list[str]],
    task_description: str,
    max_turns: int,
    termination_keyword: str,
) -> str:
    """Render the Python source for a TraceCore-compatible agent class."""

    # Build the action schema as a Python literal
    schema_lines = []
    for name, params in action_schema.items():
        schema_lines.append(f"    {name!r}: {params!r},")
    schema_block = "{\n" + "\n".join(schema_lines) + "\n}"

    # Build the agent construction code (indented for inside _consult_team)
    agent_construction = []
    for i, agent_cfg in enumerate(agents):
        aname = agent_cfg["name"]
        sys_msg = agent_cfg.get("system_message", "You are a helpful assistant.")
        sys_msg = sys_msg.replace("\\", "\\\\").replace('"', '\\"')
        agent_construction.append(
            f'        agent_{i} = AssistantAgent(\n'
            f'            name="{aname}",\n'
            f'            model_client=model_client,\n'
            f'            system_message="{sys_msg}",\n'
            f'        )'
        )
    agent_construction_block = "\n".join(agent_construction)
    agent_names = ", ".join(f"agent_{i}" for i in range(len(agents)))

    # Escape the task description for embedding in a string literal
    task_desc_escaped = task_description.replace("\\", "\\\\").replace('"', '\\"')

    lines = []
    w = lines.append

    w('"""Auto-generated TraceCore agent wrapping an AutoGen team.')
    w('')
    w('Generated by agent_bench.integrations.autogen_adapter.generate_agent().')
    w('Task action schema is baked into the prompts so the LLM always knows')
    w('which actions and parameters are valid.')
    w('')
    w('To customize:')
    w('- Edit the system messages in _consult_team()')
    w('- Add deterministic state-machine rules in act() before the LLM fallback')
    w('- Change the model or team topology')
    w('"""')
    w('')
    w('from __future__ import annotations')
    w('')
    w('import asyncio')
    w('import json')
    w('import re')
    w('')
    w('from autogen_agentchat.agents import AssistantAgent')
    w('from autogen_agentchat.teams import RoundRobinGroupChat')
    w('from autogen_agentchat.conditions import TextMentionTermination')
    w('from autogen_ext.models.openai import OpenAIChatCompletionClient')
    w('')
    w('')
    w('# Task action schema: action_name -> [required_param_names]')
    w(f'_ACTION_SCHEMA = {schema_block}')
    w('')
    w('_VALID_TYPES = set(_ACTION_SCHEMA.keys())')
    w('')
    w('')
    w('def _extract_action(text: str) -> dict | None:')
    w('    """Pull the first JSON object whose \'type\' matches a valid action."""')
    w('    candidates = []')
    w('    # Try nested JSON first (action with nested args dict)')
    w('    for match in re.finditer(r"\\{[^{}]*\\{[^{}]*\\}[^{}]*\\}", text, re.DOTALL):')
    w('        try:')
    w('            obj = json.loads(match.group())')
    w('            if "type" in obj:')
    w('                obj.setdefault("args", {})')
    w('                candidates.append(obj)')
    w('        except json.JSONDecodeError:')
    w('            continue')
    w('    # Then try flat JSON')
    w('    for match in re.finditer(r"\\{[^{}]*\\}", text, re.DOTALL):')
    w('        try:')
    w('            obj = json.loads(match.group())')
    w('            if "type" in obj:')
    w('                obj.setdefault("args", {})')
    w('                candidates.append(obj)')
    w('        except json.JSONDecodeError:')
    w('            continue')
    w('    # Prefer candidates whose type matches the valid schema')
    w('    for c in candidates:')
    w('        if c["type"] in _VALID_TYPES:')
    w('            return c')
    w('    return candidates[0] if candidates else None')
    w('')
    w('')
    w(f'class {class_name}:')
    w('    """TraceCore-compatible agent powered by an AutoGen team."""')
    w('')
    w('    def __init__(self) -> None:')
    w('        self.reset({})')
    w('')
    w('    def reset(self, task_spec):')
    w('        self.task_spec = task_spec or {}')
    w('        self.obs = None')
    w('        self.step_log: list[dict] = []')
    w('        self.learned_data: dict = {}   # data extracted from successful responses')
    w('        self.pending_wait: int = 0')
    w('        self.output_committed: bool = False')
    w('')
    w('    def observe(self, observation):')
    w('        self.obs = observation')
    w('')
    w('    def _last(self):')
    w('        if not self.obs:')
    w('            return None, None, None')
    w('        action = self.obs.get("last_action")')
    w('        result = self.obs.get("last_action_result")')
    w('        atype = action.get("type") if isinstance(action, dict) else None')
    w('        return action, result, atype')
    w('')
    w('    def _find_no_arg_action(self):')
    w('        """Find an info-gathering action (no required args, not wait/set_output)."""')
    w('        for name, params in _ACTION_SCHEMA.items():')
    w('            if not params and name not in ("wait", "set_output"):')
    w('                return {"type": name, "args": {}}')
    w('        return None')
    w('')
    w('    def _find_token_in_result(self, result):')
    w('        """Recursively search a result dict for token/key/secret values."""')
    w('        if not isinstance(result, dict):')
    w('            return None')
    w('        for k, v in result.items():')
    w('            if isinstance(v, str) and k.lower() in ("token", "secret", "key", "access_token"):')
    w('                return v')
    w('            if isinstance(v, dict):')
    w('                found = self._find_token_in_result(v)')
    w('                if found:')
    w('                    return found')
    w('        return None')
    w('')
    w('    def act(self) -> dict:')
    w('        action, last_result, action_type = self._last()')
    w('')
    w('        # Track history')
    w('        if action and last_result:')
    w('            self.step_log.append({"action": action, "result": last_result})')
    w('')
    w('        # --- Generic reactive state machine ---')
    w('        # These patterns apply to any TraceCore task.')
    w('')
    w('        # Learn from successful responses: store any returned data')
    w('        if last_result and last_result.get("ok"):')
    w('            for k, v in last_result.items():')
    w('                if k not in ("ok", "message") and v:')
    w('                    self.learned_data[k] = v')
    w('')
    w('        # After set_output succeeds, we are done')
    w('        if action_type == "set_output" and last_result and last_result.get("ok"):')
    w('            self.output_committed = True')
    w('            return {"type": "wait", "args": {"steps": 1}}')
    w('')
    w('        # After a wait (from rate limit), retry the previous non-wait action')
    w('        if action_type == "wait" and self.pending_wait > 0:')
    w('            self.pending_wait = 0')
    w('            # Find the last non-wait action to retry')
    w('            for entry in reversed(self.step_log):')
    w('                prev = entry["action"]')
    w('                if prev.get("type") != "wait":')
    w('                    return prev')
    w('')
    w('        # Handle errors from the last action')
    w('        if last_result and not last_result.get("ok") and action_type:')
    w('            error = last_result.get("error", "")')
    w('            if error == "rate_limited":')
    w('                retry_after = int(last_result.get("retry_after", 1)) or 1')
    w('                self.pending_wait = retry_after')
    w('                return {"type": "wait", "args": {"steps": retry_after}}')
    w('            if error == "temporary_failure":')
    w('                return action  # retry same action')
    w('            if error == "bad_request":')
    w('                # Clear learned data and re-gather info')
    w('                self.learned_data.clear()')
    w('                fallback = self._find_no_arg_action()')
    w('                if fallback:')
    w('                    return fallback')
    w('')
    w('        # If we found a token in the last result, commit it')
    w('        if last_result and last_result.get("ok"):')
    w('            token = self._find_token_in_result(last_result)')
    w('            if token and "set_output" in _ACTION_SCHEMA and not self.output_committed:')
    w('                # Guess the output key from the task description')
    w('                desc = self.task_spec.get("description", "")')
    w('                output_key = "ACCESS_TOKEN"  # default')
    w('                for candidate in ("ACCESS_TOKEN", "API_KEY", "SECRET", "TOKEN"):')
    w('                    if candidate in desc.upper():')
    w('                        output_key = candidate')
    w('                        break')
    w('                return {"type": "set_output", "args": {"key": output_key, "value": token}}')
    w('')
    w('        # If we have learned data, try to use it for actions that need args')
    w('        if self.learned_data and not self.output_committed:')
    w('            for act_name, required_params in _ACTION_SCHEMA.items():')
    w('                if not required_params or act_name in ("set_output", "wait"):')
    w('                    continue')
    w('                # Try to fill in required args from learned data')
    w('                args = {}')
    w('                can_fill = True')
    w('                for param in required_params:')
    w('                    if param in self.learned_data:')
    w('                        args[param] = self.learned_data[param]')
    w('                    elif param == "endpoint":')
    w('                        args[param] = "/token"  # common default')
    w('                    elif param == "payload" and "payload_template" in self.learned_data:')
    w('                        args[param] = self.learned_data["payload_template"]')
    w('                    else:')
    w('                        can_fill = False')
    w('                        break')
    w('                if can_fill:')
    w('                    return {"type": act_name, "args": args}')
    w('')
    w('        # First step or no learned data: start with info-gathering')
    w('        if not self.step_log or not self.learned_data:')
    w('            fallback = self._find_no_arg_action()')
    w('            if fallback:')
    w('                return fallback')
    w('')
    w('        # --- Fallback: consult the AutoGen team for novel situations ---')
    w('        llm_action = self._consult_team()')
    w('')
    w('        # Validate LLM output: reject actions with missing required args')
    w('        atype = llm_action.get("type", "")')
    w('        required = _ACTION_SCHEMA.get(atype, [])')
    w('        provided = set(llm_action.get("args", {}).keys())')
    w('        if required and not all(r in provided for r in required):')
    w('            fallback = self._find_no_arg_action()')
    w('            if fallback:')
    w('                return fallback')
    w('            return {"type": "wait", "args": {"steps": 1}}')
    w('')
    w('        return llm_action')
    w('')
    w('    def _build_prompt(self) -> str:')
    w('        """Build a step prompt from the current observation."""')
    w(f'        task_desc = self.task_spec.get("description", "{task_desc_escaped}")')
    w('        budget = self.obs.get("budget_remaining", {}) if self.obs else {}')
    w('        last_action = self.obs.get("last_action") if self.obs else None')
    w('        last_result = self.obs.get("last_action_result") if self.obs else None')
    w('        visible = self.obs.get("visible_state", {}) if self.obs else {}')
    w('        step = self.obs.get("step", 1) if self.obs else 1')
    w('')
    w('        actions_help = "\\n".join(')
    w("            f\"  - {name}({', '.join(params)})\"")
    w("            + (f\"  [required: {', '.join(params)}]\" if params else \"  [no args]\")")
    w('            for name, params in _ACTION_SCHEMA.items()')
    w('        )')
    w('')
    w('        parts = [')
    w('            f"TASK: {task_desc}",')
    w('            f"STEP: {step}",')
    w("            f\"BUDGET: steps={budget.get('steps','?')}, tool_calls={budget.get('tool_calls','?')}\",")
    w('            "",')
    w('            f"AVAILABLE ACTIONS (with required parameters):\\n{actions_help}",')
    w('            "",')
    w('        ]')
    w('')
    w('        if last_action and last_result:')
    w('            parts.append(f"LAST ACTION: {json.dumps(last_action)}")')
    w('            parts.append(f"LAST RESULT: {json.dumps(last_result)}")')
    w('        else:')
    w('            parts.append("This is the FIRST step. No previous action has been taken.")')
    w('        parts.append("")')
    w('')
    w('        if visible:')
    w('            parts.append(f"VISIBLE STATE: {json.dumps(visible)}")')
    w('            parts.append("")')
    w('')
    w('        if self.step_log:')
    w('            recent = self.step_log[-6:]')
    w('            history = "\\n".join(')
    w("                f\"  {json.dumps(e['action'])} -> {json.dumps(e['result'])}\"")
    w('                for e in recent')
    w('            )')
    w('            parts.append(f"RECENT HISTORY:\\n{history}")')
    w('            parts.append("")')
    w('')
    w('        action_names = list(_ACTION_SCHEMA.keys())')
    w('        example = json.dumps({"type": action_names[0], "args": {}})')
    w('        parts.append(')
    w('            "RULES:\\n"')
    w('            f"- You MUST use one of these exact action types: {action_names}.\\n"')
    w('            "- Every required arg MUST be included in the args dict.\\n"')
    w('            "- If you don\'t know a required arg value, use an info-gathering action first.\\n"')
    w('            "- If you got a rate_limited error, use wait with the retry_after value.\\n"')
    w('            "- If you got a temporary_failure, retry the same action.\\n"')
    w('            "- When you have the final answer, use set_output to store it.\\n"')
    w('            "\\n"')
    w('            f"Respond with EXACTLY one JSON object like {example} then say DONE."')
    w('        )')
    w('')
    w('        return "\\n".join(parts)')
    w('')
    w('    def _consult_team(self) -> dict:')
    w('        """Run the AutoGen team conversation and extract an action."""')
    w('        prompt = self._build_prompt()')
    w(f'        model_client = OpenAIChatCompletionClient(model="{model}")')
    w(agent_construction_block)
    w('')
    w(f'        termination = TextMentionTermination("{termination_keyword}")')
    w('        team = RoundRobinGroupChat(')
    w(f'            [{agent_names}],')
    w('            termination_condition=termination,')
    w(f'            max_turns={max_turns},')
    w('        )')
    w('')
    w('        async def execute():')
    w('            result = await team.run(task=prompt)')
    w('            return result.messages')
    w('')
    w('        try:')
    w('            messages = asyncio.run(execute())')
    w('        except RuntimeError:')
    w('            loop = asyncio.get_event_loop()')
    w('            messages = loop.run_until_complete(execute())')
    w('')
    w('        for msg in reversed(messages):')
    w('            content = getattr(msg, "content", "")')
    w('            if not content:')
    w('                continue')
    w('            action = _extract_action(content)')
    w('            if action:')
    w('                return action')
    w('')
    w('        # Fallback: wait')
    w('        return {"type": "wait", "args": {"steps": 1}}')
    w('')

    return "\n".join(lines)


def generate_agent(
    task_ref: str,
    *,
    model: str = "gpt-4o",
    agents: list[dict] | None = None,
    class_name: str = "AutoGenTeamAgent",
    max_turns: int = 4,
    termination_keyword: str = "DONE",
    output_path: str | Path = "agents/autogen_agent.py",
) -> Path:
    """Generate a TraceCore-compatible agent file from an AutoGen team definition.

    Parameters
    ----------
    task_ref:
        Task reference like ``"rate_limited_api@1"``.
    model:
        OpenAI model name for the AutoGen agents.
    agents:
        List of agent dicts, each with ``"name"`` and ``"system_message"``.
        Defaults to a Worker + Supervisor pair.
    class_name:
        Name of the generated Python class.
    max_turns:
        Maximum conversation turns per step.
    termination_keyword:
        Keyword that ends the AutoGen conversation each step.
    output_path:
        Where to write the generated agent file.

    Returns
    -------
    Path to the generated file.
    """
    if agents is None:
        agents = [
            {
                "name": "Worker",
                "system_message": (
                    "You are an action executor for a benchmark harness. "
                    "Decide the single best next action based on the task state. "
                    "Output EXACTLY one JSON object with 'type' and 'args' keys. "
                    "Then say DONE."
                ),
            },
            {
                "name": "Supervisor",
                "system_message": (
                    "Review the Worker's proposed action. "
                    "If correct, repeat the JSON verbatim and say DONE. "
                    "If wrong, correct it and say DONE. "
                    "Always output exactly one JSON action object."
                ),
            },
        ]

    # Load the task's action schema
    action_schema = _get_action_schema_for_task(task_ref)

    # Get the task description
    task_id, version = _parse_task_ref(task_ref)
    task = load_task(task_id, version)
    task_description = task.get("description", "Complete the task.")

    source = _build_agent_source(
        class_name=class_name,
        model=model,
        agents=agents,
        action_schema=action_schema,
        task_description=task_description,
        max_turns=max_turns,
        termination_keyword=termination_keyword,
    )

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(source, encoding="utf-8")
    print(f"Generated TraceCore agent: {out}")
    print(f"  Class: {class_name}")
    print(f"  Model: {model}")
    print(f"  Agents: {[a['name'] for a in agents]}")
    print(f"  Task schema: {list(action_schema.keys())}")
    print(f"\nRun with:")
    print(f"  agent-bench run --agent {out} --task {task_ref} --seed 42")
    return out
