"""TraceCore adapter for OpenClaw agent 'log-monitor'.

Auto-generated by `agent-bench openclaw`. This adapter is self-contained:
no live OpenClaw gateway is required. Fill in the act() method with your
decision logic, then test with:

    agent-bench run --agent log-monitor_adapter_agent.py --task <task_ref> --seed 0

To use the live OpenClaw gateway instead, re-scaffold with --gateway.
"""
# Prompt (first line): # Log Monitor Agent

from __future__ import annotations

AGENT_ID = 'log-monitor'  # OpenClaw model: anthropic/claude-sonnet-4-5


class LogMonitorAdapterAgent:
    """Self-contained TraceCore adapter for OpenClaw agent 'log-monitor'.

    Replace the TODO block in act() with logic that maps the TraceCore
    observation to a task action dict.
    """

    def reset(self, task_spec: dict) -> None:
        """Called once before each episode."""
        self.task_spec = task_spec or {}
        self.obs: dict | None = None
        self.step = 0
        self._listed_paths: set[str] = set()
        self._parsed_files: set[str] = set()
        self._failed_reads: set[str] = set()
        self._target_key: str | None = None
        self._alert_code: str | None = None
        self._output_sent = False

    def observe(self, observation: dict) -> None:
        """Receive the latest environment observation."""
        self.obs = observation

    def act(self) -> dict:
        """Return the next action dict.

        Action schema::

            {"type": "<action_type>", "args": {...}}

        Use {"type": "set_output", "args": {"key": ..., "value": ...}} to
        submit the final answer and end the episode successfully.
        """
        self.step += 1

        if self.obs is None:
            return {"type": "wait", "args": {}}

        budget = self.obs.get("budget_remaining", {})
        remaining_steps = budget.get("steps", 0)
        remaining_tool_calls = budget.get("tool_calls", 0)

        self._ingest_last_result()

        if self._target_key and self._alert_code and not self._output_sent:
            self._output_sent = True
            return {
                "type": "set_output",
                "args": {"key": self._target_key, "value": self._alert_code},
            }

        if remaining_steps <= 1 or remaining_tool_calls <= 1:
            return {"type": "wait", "args": {}}

        visible = self.obs.get("visible_state", {}) or {}
        files_seen = visible.get("files_seen", []) or []

        if "/app" not in self._listed_paths:
            return {"type": "list_dir", "args": {"path": "/app"}}

        next_file = self._next_file_to_read(files_seen)
        if next_file:
            return {"type": "read_file", "args": {"path": next_file}}

        if self._target_key and self._alert_code and not self._output_sent:
            self._output_sent = True
            return {
                "type": "set_output",
                "args": {"key": self._target_key, "value": self._alert_code},
            }

        return {"type": "wait", "args": {}}

    def _ingest_last_result(self) -> None:
        if not self.obs:
            return

        last_action = self.obs.get("last_action") or {}
        last_result = self.obs.get("last_action_result") or {}
        action_type = last_action.get("type")
        if not action_type:
            return

        if action_type == "list_dir" and last_result.get("ok"):
            path = last_action.get("args", {}).get("path")
            if path:
                self._listed_paths.add(path)
            return

        if action_type == "read_file":
            path = last_action.get("args", {}).get("path")
            if not path:
                return
            if not last_result.get("ok"):
                self._failed_reads.add(path)
                return
            content = last_result.get("content", "") or ""
            self._parsed_files.add(path)
            self._extract_key_values(content)

    def _extract_key_values(self, content: str) -> None:
        for line in content.splitlines():
            line = line.strip()
            if not line or "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip()
            if key == "TARGET_KEY" and not self._target_key:
                self._target_key = value
            if key == "ALERT_CODE" and not self._alert_code:
                self._alert_code = value

    def _next_file_to_read(self, files_seen: list[str]) -> str | None:
        priority = [
            "/app/README.md",
            "/app/incident.log",
            "/app/service.log",
            "/app/telemetry_snapshot.txt",
        ]
        candidates = []
        for path in priority:
            if path in files_seen and path not in self._parsed_files and path not in self._failed_reads:
                return path

        for path in files_seen:
            if path not in self._parsed_files and path not in self._failed_reads:
                candidates.append(path)

        return candidates[0] if candidates else None
