"""Auto-generated TraceCore agent wrapping an AutoGen team.

Generated by agent_bench.integrations.autogen_adapter.generate_agent().
Task action schema is baked into the prompts so the LLM always knows
which actions and parameters are valid.

To customize:
- Edit the system messages in _consult_team()
- Add deterministic state-machine rules in act() before the LLM fallback
- Change the model or team topology
"""

from __future__ import annotations

import asyncio
import json
import re

from autogen_agentchat.agents import AssistantAgent
from autogen_agentchat.teams import RoundRobinGroupChat
from autogen_agentchat.conditions import TextMentionTermination
from autogen_ext.models.openai import OpenAIChatCompletionClient


# Task action schema: action_name -> [required_param_names]
_ACTION_SCHEMA = {
    'call_api': ['endpoint', 'payload'],
    'get_client_config': [],
    'inspect_status': [],
    'set_output': ['key', 'value'],
    'wait': ['steps'],
}

_VALID_TYPES = set(_ACTION_SCHEMA.keys())


def _extract_action(text: str) -> dict | None:
    """Pull the first JSON object whose 'type' matches a valid action."""
    candidates = []
    # Try nested JSON first (action with nested args dict)
    for match in re.finditer(r"\{[^{}]*\{[^{}]*\}[^{}]*\}", text, re.DOTALL):
        try:
            obj = json.loads(match.group())
            if "type" in obj:
                obj.setdefault("args", {})
                candidates.append(obj)
        except json.JSONDecodeError:
            continue
    # Then try flat JSON
    for match in re.finditer(r"\{[^{}]*\}", text, re.DOTALL):
        try:
            obj = json.loads(match.group())
            if "type" in obj:
                obj.setdefault("args", {})
                candidates.append(obj)
        except json.JSONDecodeError:
            continue
    # Prefer candidates whose type matches the valid schema
    for c in candidates:
        if c["type"] in _VALID_TYPES:
            return c
    return candidates[0] if candidates else None


class AutoGenTeamAgent:
    """TraceCore-compatible agent powered by an AutoGen team."""

    def __init__(self) -> None:
        self.reset({})

    def reset(self, task_spec):
        self.task_spec = task_spec or {}
        self.obs = None
        self.step_log: list[dict] = []
        self.learned_data: dict = {}   # data extracted from successful responses
        self.pending_wait: int = 0
        self.output_committed: bool = False

    def observe(self, observation):
        self.obs = observation

    def _last(self):
        if not self.obs:
            return None, None, None
        action = self.obs.get("last_action")
        result = self.obs.get("last_action_result")
        atype = action.get("type") if isinstance(action, dict) else None
        return action, result, atype

    def _find_no_arg_action(self):
        """Find an info-gathering action (no required args, not wait/set_output)."""
        for name, params in _ACTION_SCHEMA.items():
            if not params and name not in ("wait", "set_output"):
                return {"type": name, "args": {}}
        return None

    def _find_token_in_result(self, result):
        """Recursively search a result dict for token/key/secret values."""
        if not isinstance(result, dict):
            return None
        for k, v in result.items():
            if isinstance(v, str) and k.lower() in ("token", "secret", "key", "access_token"):
                return v
            if isinstance(v, dict):
                found = self._find_token_in_result(v)
                if found:
                    return found
        return None

    def act(self) -> dict:
        action, last_result, action_type = self._last()

        # Track history
        if action and last_result:
            self.step_log.append({"action": action, "result": last_result})

        # --- Generic reactive state machine ---
        # These patterns apply to any TraceCore task.

        # Learn from successful responses: store any returned data
        if last_result and last_result.get("ok"):
            for k, v in last_result.items():
                if k not in ("ok", "message") and v:
                    self.learned_data[k] = v

        # After set_output succeeds, we are done
        if action_type == "set_output" and last_result and last_result.get("ok"):
            self.output_committed = True
            return {"type": "wait", "args": {"steps": 1}}

        # After a wait (from rate limit), retry the previous non-wait action
        if action_type == "wait" and self.pending_wait > 0:
            self.pending_wait = 0
            # Find the last non-wait action to retry
            for entry in reversed(self.step_log):
                prev = entry["action"]
                if prev.get("type") != "wait":
                    return prev

        # Handle errors from the last action
        if last_result and not last_result.get("ok") and action_type:
            error = last_result.get("error", "")
            if error == "rate_limited":
                retry_after = int(last_result.get("retry_after", 1)) or 1
                self.pending_wait = retry_after
                return {"type": "wait", "args": {"steps": retry_after}}
            if error == "temporary_failure":
                return action  # retry same action
            if error == "bad_request":
                # Clear learned data and re-gather info
                self.learned_data.clear()
                fallback = self._find_no_arg_action()
                if fallback:
                    return fallback

        # If we found a token in the last result, commit it
        if last_result and last_result.get("ok"):
            token = self._find_token_in_result(last_result)
            if token and "set_output" in _ACTION_SCHEMA and not self.output_committed:
                # Guess the output key from the task description
                desc = self.task_spec.get("description", "")
                output_key = "ACCESS_TOKEN"  # default
                for candidate in ("ACCESS_TOKEN", "API_KEY", "SECRET", "TOKEN"):
                    if candidate in desc.upper():
                        output_key = candidate
                        break
                return {"type": "set_output", "args": {"key": output_key, "value": token}}

        # If we have learned data, try to use it for actions that need args
        if self.learned_data and not self.output_committed:
            for act_name, required_params in _ACTION_SCHEMA.items():
                if not required_params or act_name in ("set_output", "wait"):
                    continue
                # Try to fill in required args from learned data
                args = {}
                can_fill = True
                for param in required_params:
                    if param in self.learned_data:
                        args[param] = self.learned_data[param]
                    elif param == "endpoint":
                        args[param] = "/token"  # common default
                    elif param == "payload" and "payload_template" in self.learned_data:
                        args[param] = self.learned_data["payload_template"]
                    else:
                        can_fill = False
                        break
                if can_fill:
                    return {"type": act_name, "args": args}

        # First step or no learned data: start with info-gathering
        if not self.step_log or not self.learned_data:
            fallback = self._find_no_arg_action()
            if fallback:
                return fallback

        # --- Fallback: consult the AutoGen team for novel situations ---
        llm_action = self._consult_team()

        # Validate LLM output: reject actions with missing required args
        atype = llm_action.get("type", "")
        required = _ACTION_SCHEMA.get(atype, [])
        provided = set(llm_action.get("args", {}).keys())
        if required and not all(r in provided for r in required):
            fallback = self._find_no_arg_action()
            if fallback:
                return fallback
            return {"type": "wait", "args": {"steps": 1}}

        return llm_action

    def _build_prompt(self) -> str:
        """Build a step prompt from the current observation."""
        task_desc = self.task_spec.get("description", "Retrieve ACCESS_TOKEN while honoring rate limits and transient errors.")
        budget = self.obs.get("budget_remaining", {}) if self.obs else {}
        last_action = self.obs.get("last_action") if self.obs else None
        last_result = self.obs.get("last_action_result") if self.obs else None
        visible = self.obs.get("visible_state", {}) if self.obs else {}
        step = self.obs.get("step", 1) if self.obs else 1

        actions_help = "\n".join(
            f"  - {name}({', '.join(params)})"
            + (f"  [required: {', '.join(params)}]" if params else "  [no args]")
            for name, params in _ACTION_SCHEMA.items()
        )

        parts = [
            f"TASK: {task_desc}",
            f"STEP: {step}",
            f"BUDGET: steps={budget.get('steps','?')}, tool_calls={budget.get('tool_calls','?')}",
            "",
            f"AVAILABLE ACTIONS (with required parameters):\n{actions_help}",
            "",
        ]

        if last_action and last_result:
            parts.append(f"LAST ACTION: {json.dumps(last_action)}")
            parts.append(f"LAST RESULT: {json.dumps(last_result)}")
        else:
            parts.append("This is the FIRST step. No previous action has been taken.")
        parts.append("")

        if visible:
            parts.append(f"VISIBLE STATE: {json.dumps(visible)}")
            parts.append("")

        if self.step_log:
            recent = self.step_log[-6:]
            history = "\n".join(
                f"  {json.dumps(e['action'])} -> {json.dumps(e['result'])}"
                for e in recent
            )
            parts.append(f"RECENT HISTORY:\n{history}")
            parts.append("")

        action_names = list(_ACTION_SCHEMA.keys())
        example = json.dumps({"type": action_names[0], "args": {}})
        parts.append(
            "RULES:\n"
            f"- You MUST use one of these exact action types: {action_names}.\n"
            "- Every required arg MUST be included in the args dict.\n"
            "- If you don't know a required arg value, use an info-gathering action first.\n"
            "- If you got a rate_limited error, use wait with the retry_after value.\n"
            "- If you got a temporary_failure, retry the same action.\n"
            "- When you have the final answer, use set_output to store it.\n"
            "\n"
            f"Respond with EXACTLY one JSON object like {example} then say DONE."
        )

        return "\n".join(parts)

    def _consult_team(self) -> dict:
        """Run the AutoGen team conversation and extract an action."""
        prompt = self._build_prompt()
        model_client = OpenAIChatCompletionClient(model="gpt-5-nano")
        agent_0 = AssistantAgent(
            name="Worker",
            model_client=model_client,
            system_message="Execute tools precisely. Output one JSON action then say DONE.",
        )
        agent_1 = AssistantAgent(
            name="Supervisor",
            model_client=model_client,
            system_message="Review the action. Correct if wrong. Say DONE.",
        )

        termination = TextMentionTermination("DONE")
        team = RoundRobinGroupChat(
            [agent_0, agent_1],
            termination_condition=termination,
            max_turns=4,
        )

        async def execute():
            result = await team.run(task=prompt)
            return result.messages

        try:
            messages = asyncio.run(execute())
        except RuntimeError:
            loop = asyncio.get_event_loop()
            messages = loop.run_until_complete(execute())

        for msg in reversed(messages):
            content = getattr(msg, "content", "")
            if not content:
                continue
            action = _extract_action(content)
            if action:
                return action

        # Fallback: wait
        return {"type": "wait", "args": {"steps": 1}}
