"""TraceCore gateway adapter for OpenClaw agent 'log-monitor'.

Auto-generated by `agent-bench openclaw --gateway`. Requires a running
OpenClaw gateway. Pass a gateway client at construction time:

    from my_openclaw_sdk import OpenClawClient
    agent = LogMonitorGatewayAdapterAgent(client=OpenClawClient())
    agent-bench run --agent log-monitor_gateway_adapter_agent.py --task <task_ref> --seed 0

agent.wait default timeout is 30 s; increase via OPENCLAW_WAIT_TIMEOUT_MS env var.
"""

from __future__ import annotations
import os

AGENT_ID = 'log-monitor'  # OpenClaw model: anthropic/claude-sonnet-4-5
_WAIT_TIMEOUT_MS = int(os.environ.get("OPENCLAW_WAIT_TIMEOUT_MS", "25000"))


class LogMonitorGatewayAdapterAgent:
    """Gateway-wired TraceCore adapter for OpenClaw agent 'log-monitor'.

    The gateway client must implement:
        client.agent(agent_id, prompt) -> {"runId": str}
        client.agent_wait(run_id, timeout_ms) -> {"status": "ok"|"error"|"timeout", "action": dict}
    """

    def __init__(self, client=None) -> None:
        self._client = client
        self.obs: dict | None = None
        self.task_spec: dict = {}

    def reset(self, task_spec: dict) -> None:
        self.task_spec = task_spec or {}
        self.obs = None

    def observe(self, observation: dict) -> None:
        self.obs = observation

    def act(self) -> dict:
        if self.obs is None:
            return {"type": "wait", "args": {}}

        remaining_steps = self.obs.get("remaining_steps", 0)
        remaining_tool_calls = self.obs.get("remaining_tool_calls", 0)

        if remaining_steps <= 1 or remaining_tool_calls <= 1:
            return {"type": "wait", "args": {}}

        if self._client is None:
            raise RuntimeError(
                f"No gateway client provided. Pass client= to {type(self).__name__}()."
            )

        run = self._client.agent(AGENT_ID, prompt=str(self.obs))
        result = self._client.agent_wait(run["runId"], timeout_ms=_WAIT_TIMEOUT_MS)

        if result.get("status") != "ok":
            return {"type": "wait", "args": {}}

        # TODO: translate the agent_end payload into a TraceCore action dict.
        # Your plugin's agent_end hook should populate result["action"].
        return result.get("action") or {"type": "wait", "args": {}}
